# Generated by Django 3.0.3 on 2020-03-06 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField(max_length=300)),
                ('Offer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Available', models.IntegerField(default=0)),
                ('Premimum', models.BooleanField(default=False)),
                ('Brand', models.CharField(max_length=50)),
                ('Quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('p_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('Image1', models.ImageField(default='', upload_to='shop/image')),
                ('Image2', models.ImageField(default='', upload_to='shop/image')),
                ('Image3', models.ImageField(default='', upload_to='shop/image')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name', max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
