# Generated by Django 3.0.3 on 2020-03-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200307_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(choices=[('S size', 'S size'), ('M size', 'M size'), ('L size', 'L size')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Violet', 'Violet'), ('Gold', 'Gold'), ('Coral', 'Coral'), ('Brown', 'Brown'), ('White', 'white'), ('Black', 'Black'), ('Silver', 'Silver')], default='none', max_length=15),
        ),
    ]
