# Generated by Django 3.0.3 on 2020-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200311_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='product_rate',
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delevered_date',
            field=models.DateField(default=''),
        ),
    ]
