# Generated by Django 3.0.3 on 2020-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200311_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='delevered_date',
            field=models.DateField(null=True),
        ),
    ]
