# Generated by Django 3.0.3 on 2020-03-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200312_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='countery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countery_name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_name', models.CharField(default='', max_length=40)),
                ('In_countery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.countery')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disteict_name', models.CharField(default='', max_length=40)),
                ('In_states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sates')),
            ],
        ),
    ]
