# Generated by Django 3.0.3 on 2020-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_countery_district_sates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sates',
            new_name='states',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='Disteict_name',
            new_name='District_name',
        ),
    ]
