# Generated by Django 3.0.3 on 2020-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200312_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='states',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='In_states',
            new_name='In_state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='states_name',
            new_name='state_name',
        ),
        migrations.AddField(
            model_name='district',
            name='Ofstate',
            field=models.CharField(default='', max_length=40),
        ),
    ]
