# Generated by Django 3.0.3 on 2020-03-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200327_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='delevered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
