# Generated by Django 3.0.3 on 2020-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200416_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=100)),
                ('userid', models.IntegerField(default=0)),
                ('productid', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('orderdate', models.DateField()),
                ('Track', models.CharField(default='', max_length=40)),
                ('deletedate', models.DateField()),
            ],
        ),
    ]
